# Generated by Django 4.2.29 on 2026-03-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Body',
            new_name='body',
        ),
    ]
